# Copyright 2024 Ant Group.
# this corresponds to the default config
train:
  dataset_path: ImageNet:split=TRAIN
  OFFICIAL_EPOCH_LENGTH: 625
  batch_size_per_gpu: 64  # 32 gpus
crops:
  local_crops_number: 8
optim:
  epochs: 346 # effective epochs: 1200
  warmup_epochs: 30
  ibot_activate_epochs: 30
  iter_num_scale: 0.9
evaluation:
  eval_period_iterations: 21625 # total iter: 216250 * 2 = 432500



